JOKES = [
    "Why don’t scientists trust atoms? Because they make up everything!",
    "What do you call fake spaghetti? An impasta!",
    "Why did the math book look sad? Because it had too many problems.",
    "How does a snowman get around? By riding an “icicle.”",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why was the big cat disqualified from the race? Because it was a cheetah!",
    "What’s orange and sounds like a parrot? A carrot.",
    "Why can't you give Elsa a balloon? Because she will let it go.",
    "How do you organize a space party? You planet.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "What do you call a bear with no teeth? A gummy bear.",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "What does a cloud wear under his raincoat? Thunderwear.",
    "Why did the computer go to the doctor? It had a virus!",
    "Why was the math book sad? It had too many problems.",
    "What did one hat say to the other hat? Stay here, I'm going on ahead!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What do you get when you cross a snowman and a dog? Frostbite!",
    "How do you catch a squirrel? Climb a tree and act like a nut!",
    "What do you call a lazy kangaroo? A pouch potato.",
    "Why did the scarecrow become a successful neurosurgeon? He was outstanding in his field.",
    "What do you call a fish wearing a bowtie? Sofishticated.",
    "How do you make a tissue dance? Put a little boogie in it.",
    "Why don't you ever see elephants hiding in trees? Because they're so good at it.",
    "What do you call a sleeping bull? A bulldozer.",
    "Why did the coffee file a police report? It got mugged!",
    "What’s brown and sticky? A stick.",
    "Why was the belt arrested? For holding up a pair of pants!",
    "What do you call a fish with no eyes? Fsh.",
    "Why did the bike fall over? It was two-tired.",
    "What kind of tree fits in your hand? A palm tree.",
    "Why don’t seagulls fly over the bay? Because then they’d be bagels!",
    "What does a grape do when it gets stepped on? Nothing but let out a little wine.",
]